name: sayaraty
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^4.3.0
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0
  flutter_riverpod: ^3.0.3
  go_router: ^13.2.5
  equatable: ^2.0.7
  dartz: ^0.10.1
  http: ^1.2.0
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  firebase_storage: ^13.0.5
  image_picker: ^1.2.1  # pour galerie/camera
  file_picker: ^10.3.7    # pour PDF (optionnel si vous voulez seulement des images)
  mime: ^2.0.0
  uuid: ^4.4.2
  photo_view: ^0.15.0
  share_plus: ^10.0.2
  path_provider: ^2.1.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0

# -----------------------
# FLUTTER
# -----------------------
flutter:
  uses-material-design: true

  assets:
    - assets/images/logo_sayaraty.png

# -----------------------
# SPLASH SCREEN
# -----------------------
flutter_native_splash:
  color: "#F5F7FB"
  image: assets/images/logo_sayaraty.png
  android: true
  ios: true

  android_12:
    image: assets/images/logo_sayaraty.png
    color: "#F5F7FB"


# -----------------------
# APP ICON
# -----------------------
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo_sayaraty.png"
  #adaptive_icon_background: "#1E3A8A"
  adaptive_icon_foreground: "assets/images/logo_sayaraty.png"
  adaptive_icon_background: "#F5F7FB"